version: "3.8"
services:
  cdk:
    build:
      context: .
      dockerfile: Dockerfile
    image: cdk
    container_name: cdk
    tty: true
    volumes:
      - .:/home
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_DEFAULT_REGION: ${AWS_DEFAULT_REGION}
      AWS_DEFAULT_OUTPUT: ${AWS_DEFAULT_OUTPUT}
