name: CI for NetworkStack

on:
  push:
    branches:
      - main
    paths:
      - 'hello_world_app/**'
  pull_request:
    branches:
      - main
    paths:
      - 'hello_world_app/**'

defaults:
  run:
    working-directory: hello_world_app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - run: npm ci
      - run: npm run build
      - run: npm test